apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fpt-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: fpt-frontend-svc
          servicePort: 80
      - path: /api
        backend:
          serviceName: fpt-backend-svc
          servicePort: 80
