env:
  - FPT_SERVICE=frontend
  - FPT_SERVICE=backend
os: linux
dist: focal
language: minimal
services:
  - docker
script:
  - docker build -t fpt/fpt-$FPT_SERVICE $FPT_SERVICE

jobs:
  include:
    - os: linux
      dist: focal
      language: minimal
      services:
        - docker
      install:
        - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
        - chmod +x ./kind
        - mv ./kind .local/bin/kind
        - export PATH=~/.local/bin:$PATH
        - kind create cluster
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - make install
