version: '3'

services:
  reverse-proxy:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - "./conf:/etc/nginx/conf.d"
  redis-primary:
    image: redis:alpine
    ports:
      - "6379:6379"
