name: build-containers
on:
  - pull_request

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend
    steps:
      - name: Build and push
        working-directory: ${{ matrix.service }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: fpt/fpt-${{ matrix.service }}
