name: build-containers
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - if: github.event_name == 'push' && github.ref == 'master'
        name: Build fpt/fpt-${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.service }}/Dockerfile
          pull: true
          push: true
          context: ${{ matrix.service }}
          tags: ghcr.io/dhackz/fpt/fpt-${{ matrix.service }}:latest
      - if: github.event_name == 'pull_request'
        name: Build fpt/fpt-${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.service }}/Dockerfile
          pull: true
          push: true
          context: ${{ matrix.service }}
          tags: ghcr.io/dhackz/fpt/fpt-${{ matrix.service }}:${{ github.head_ref }}
