name: build-containers
strategy:
  matrix:
    service:
      - frontend
      - backend
on:
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.service }}
          tags: fpt/fpt-${{ matrix.service }}
