name: build-containers
on:
  - pull_request

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend
    steps:
      - uses: actions/checkout@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build fpt/fpt-${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.service }}/Dockerfile
          pull: true
          push: true
          context: ${{ matrix.service }}
          tags: ghcr.io/fpt/fpt-${{ matrix.service }}:${{ github.head_ref }}
