name: build-containers
on:
  - pull_request

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend
    steps:
      - uses: actions/checkout@master
      - name: Echo working diretory
        run: pwd
      - name: Echo working diretory
        run: ls
      - name: Build docker image
        run: docker build -t fpt/fpt-${{ matrix.service }} ${{ matrix.service }}
