name: build-containers
on:
  - pull_request

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend
    steps:
      - uses: actions/checkout@master

      - name: Build against builder2
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.service }}/Dockerfile
          context: ${{ matrix.service }}
          tags: fpt/fpt-${{ matrix.service }}
