name: "Create cluster using KinD"
on: [pull_request]

jobs:
  helm-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build fpt/fpt-frontend
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          pull: true
          push: true
          context: backend
          tags: localhost:5000/fpt/fpt-backend:latest

      - name: Build fpt/fpt-frontend
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          pull: true
          push: true
          context: frontend 
          tags: localhost:5000/fpt/fpt-frontend:latest

      - uses: engineerd/setup-kind@v0.4.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
