name: "Create cluster using KinD"
on: [pull_request]

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build fpt/fpt-backend
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          context: backend
          load: true
          pull: true
          tags: fpt/fpt-backend:dev

      - name: Build fpt/fpt-frontend
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          context: frontend 
          load: true
          pull: true
          tags: pt/fpt-frontend:dev

      - uses: engineerd/setup-kind@v0.4.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Pull local registry image and load into kind
        run: |
          kind load docker-image fpt/fpt-backend:dev
          kind load docker-image fpt/fpt-frontend:dev

      - name: Install helm charts in kind
        run: echo "Should helm install but lets continue with that later"
