name: "Integration"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build fpt/fpt-backend
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          context: backend
          load: true
          pull: true
          tags: fpt/fpt-backend:dev

      - name: Build fpt/fpt-frontend
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          context: frontend 
          load: true
          pull: true
          tags: fpt/fpt-frontend:dev

      - name: Write KinD config with ingress
        run: |
          cat <<EOF > kindconfig.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            kubeadmConfigPatches:
            - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  node-labels: "ingress-ready=true"
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          EOF

      - uses: engineerd/setup-kind@v0.4.0
        with:
          config: kindconfig.yaml
      - name: Install nginx kind ingress
        run: kubectl apply --wait -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

      - name: Wait for ingress
        run: |
          while [[ \
            $(kubectl get pods \
                -l app.kubernetes.io/component=controller \
                -n ingress-nginx \
                -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" \
          ]]; \
          do echo "waiting for pods" && sleep 1; done

      - name: Load images into kind
        run: |
          kind load docker-image fpt/fpt-backend:dev
          kind load docker-image fpt/fpt-frontend:dev

      - name: Install helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Install helm charts
        run: helm upgrade --wait --install --devel fpt ./fpt-charts 

      - name: Run backend api tests
        run: docker run --network=host --rm -v $(pwd)/tests/postman:/opt/postman postman/newman run /opt/postman/fpt.postman_collection.json

      - name: Install google-chrome
        run: sudo apt-get update && sudo apt-get install google-chrome
      - name: Run backend api tests
        working-directory: tests/webdriver
        run: yarn install && yarn wdio wdio.conf.js
